name = "SemiseparableMatrices"
uuid = "f8ebbe35-cbfb-4060-bf7f-b10e4670cf57"
authors = ["Sheehan Olver <solver@mac.com>"]
version = "0.1.0"

[deps]
ArrayLayouts = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
